### ISSUE TITLE
Language not selected on Safari

### ISSUE THREAD

**Issue by tsubik** [Vizzuality/trase#333]
When I clear all the app related data from localStorage and sessionStorage and reopen any page without having language set in URL then the language seems to be not selected. I noticed that on Safari, and all devices I've checked on have only Polish language set. 

![image](https://user-images.githubusercontent.com/1286444/37087551-e652bef2-21fa-11e8-95f5-15590026f3d5.png)

**Comment by tiagojsag** [comment]
I believe this is fixed, closing

**Comment by tsubik** [comment]
Just checked and it's unfortunately not, at least on my iPad that problem is still present. Tested also on Chrome on that iPad and the same issue.
